# Generated by Django 4.2.5 on 2023-09-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
    ]
