# Generated by Django 4.2.5 on 2023-09-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
