# Generated by Django 4.2.5 on 2023-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='key',
            field=models.SlugField(default='valor_predeterminado', unique=True, verbose_name='Nombre clave'),
        ),
    ]
